using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MDDBooster
{
    internal class Constants
    {
        public const string NO_NOT_EDIT_MESSAGE = "Code generated by \"MDD Booster\"; DO NOT EDIT.";
    }
}
